-- Purchase receipts for founding members.
--
-- Run this AFTER 20260801000000_founding_members.sql - it extends that table.
--
-- Every membership gets a human-readable, sequential receipt number
-- (VW-2026-00001) that goes out in the confirmation email and is what a buyer
-- would quote when asking about their purchase. It is generated by the database
-- rather than the app so it stays unique and gap-free even if two payments land
-- at the same instant, and so a receipt can never exist without a number.

create sequence if not exists public.founding_member_receipt_seq;

alter table public.founding_members
  add column if not exists receipt_number text,
  add column if not exists receipt_email_sent_at timestamptz;

-- Number any rows written before this migration (e.g. a payment that landed
-- between the two migrations) so the not-null below can be applied.
update public.founding_members
set receipt_number = 'VW-' || to_char(created_at, 'YYYY') || '-'
      || lpad(nextval('public.founding_member_receipt_seq')::text, 5, '0')
where receipt_number is null;

alter table public.founding_members
  alter column receipt_number set default
    'VW-' || to_char(now(), 'YYYY') || '-'
      || lpad(nextval('public.founding_member_receipt_seq')::text, 5, '0');

alter table public.founding_members
  alter column receipt_number set not null;

create unique index if not exists founding_members_receipt_number_key
  on public.founding_members (receipt_number);
